# docker-compose-standard.yaml
name: dockercomposeexample_standard

services:
  web:
    container_name: "web-1"
    build:
      context:    .
      dockerfile: Dockerfile
    ports:
      - "8001:5000"
  redis:
    container_name: "redis-1"
    image:          "redis:alpine"
    networks:
      default:
        aliases:
          - redis
