DROP DATABASE IF EXISTS ToDelete;
CREATE DATABASE IF NOT EXISTS ToDelete;
CREATE USER IF NOT EXISTS 'installer'@'%' IDENTIFIED BY 'N0Pa55wrd';
GRANT ALL ON ToDelete.* TO 'installer'@'%';
FLUSH PRIVILEGES;
